[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/auth/session"
healthcheckTimeout = 300
startCommand = "node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
